CC=g++

bubble: bubbleSort.cpp utils.cpp
	$(CC) -o bubbleSort bubbleSort.cpp utils.cpp

insert: insertionSort.cpp utils.cpp
	$(CC) -o insertionSort insertionSort.cpp utils.cpp

quick: quickSort.cpp utils.cpp
	$(CC) -o quickSort quickSort.cpp utils.cpp

select: selectionSort.cpp utils.cpp
	$(CC) -o selectionSort selectionSort.cpp utils.cpp

merge: mergeSort.cpp utils.cpp
	$(CC) -o mergeSort mergeSort.cpp utils.cpp

clean:
	rm -rf bubbleSort insertionSort quickSort selectionSort mergeSort